### ISSUE TITLE
Warning with soulbound enchantment and twilight forest charms

### ISSUE THREAD

**Issue by Caopr** [TheIllusiveC4/CorpseComplex#9]
My soulbound armor was destroyed upon dying with twilight forest charms of keeping and charm of life. just informing of the conflict. nice mod tho have enjoyed it so far

**Comment by TheIllusiveC4** [comment]
Thanks for informing me. I'll look into this issue.

**Comment by TheIllusiveC4** [comment]
It looks like this is caused mainly by a conflict with the Charm of Life. Basically what's happening is that this mod attempts to store your valuables upon death and then gives them back to you when you respawn. The Charm of Life intercepts this process and cancels the death, leaving your valuables in a state of limbo where they were stored but never given back. I'll try and code a workaround for this conflict.

**Comment by TheIllusiveC4** [comment]
I've just pushed out a new update, version 1.0.1.2, that should fix this issue. Please let me know if the problem continues so I can reopen this. Thank you very much for notifying me of this conflict.

**Comment by Caopr** [comment]
I tried in creative then survival against a wither with a set of 4 soulbound armor pieces and a soulbound weapon. having 1 charm of life worked fine. but once I had multiple charms of keeping and life it still happened. and soulbound items dissapered and were not on the ground It could be a combination of having both at once

**Comment by Caopr** [comment]
I will note that it also seems to affect soulbound item types from another mod that gives the option to soulbind tinkers weapons using a nether star

**Comment by TheIllusiveC4** [comment]
Since you said that this conflict also happens with other mods, I took a closer look at the Twilight Forest code for the charms. I think what's happening is what I mentioned before, except it's actually happening on Twilight Forest's end. The Charm of Keeping fires, keeping the relevant items in storage, and removes them from your inventory. Then the Charm of Life fires and cancels the death, leaving the items that were kept by the Charm of Keeping in a state of limbo as they never check for that. 

I tested this in an instance without Corpse Complex even loaded. My non-soulbound armor was destroyed also when using both Charm of Life I and Charm of Keeping I. 

I'll try to code a workaround for this, but my attempts so far have failed so I think this may be outside my reach. I recommend opening up an issue on Twilight Forest's tracker about this since I think they're the ones most easily able to solve this. If they point back to my mod as being the problem, then I'll take another look at my thought process.

**Comment by Caopr** [comment]
Odd for me it wouldent affect anything but soulbound items. ive made an issue over on the twilight forest page.
https://github.com/TeamTwilight/twilightforest/issues/338

**Comment by TheIllusiveC4** [comment]
That is strange. Did you make sure that the non-soulbound items were relevant to the Charm of Keeping? If you always wear Soulbound armor and only hold Soulbound tools, then it might seem like it only affects soulbound items when in reality it affects anything stored by Charm of Keeping. 

If that's not the case, then I'm afraid I'm not sure what's happening then. I can replicate this behavior reliably on my end with only Twilight Forest installed, at the very least.

**Comment by Caopr** [comment]
After the soulbounds went bye bye I kept dying for a bit with a full inventory. and my items stayed And the first time it happened I still had my boots equipped. which I hadent yet gotten soulbinding for.

**Comment by TheIllusiveC4** [comment]
Hm, I'm honestly not sure what's happening there then. I'll wait and see how the Twilight Forest issue resolves before re-investigating on my end.
